apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: recommendation
  namespace: canary-release
spec:
  host: recommendation
  subsets:
  - labels:
      app: recommendation
    name: stable
  - labels:
      app: recommendation
    name: canary
---