apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: blue-green
  labels:
    app: customer
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
      version: v1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_DB
            value: recommendation
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            value: admin123